export const GET_TABLE_DATA_REQUEST = "GET_TABLE_DATA_REQUEST";
export const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
export const GET_TABLE_DATA_FAILURE = "GET_TABLE_DATA_FAILURE";

export const GET_APP_DATA_REQUEST = "GET_APP_DATA_REQUEST";
export const GET_APP_DATA_SUCCESS = "GET_APP_DATA_SUCCESS";
export const GET_APP_DATA_FAILURE = "GET_APP_DATA_FAILURE";

export const DATE_RANGE = "DATE_RANGE";
export const SET_COLUMN = "SET_COLUMN";

export const SET_SORTED = "SET_SORTED";
export const SET_FILTER = "SET_FILTER";